// Core schema
import { pgTable, varchar, text, timestamp, integer, boolean, uuid, numeric } from 'drizzle-orm/pg-core';
export const per_person = pgTable('per_person', { id: uuid('id').primaryKey().defaultRandom(), first_name: varchar('first_name',{length:120}).notNull(), last_name: varchar('last_name',{length:120}).notNull(), email: varchar('email',{length:256}).notNull(), phone: varchar('phone',{length:64}), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const per_candidate = pgTable('per_candidate', { id: uuid('id').primaryKey().defaultRandom(), person_id: uuid('person_id').notNull(), status: varchar('status',{length:48}).notNull().default('new'), location: varchar('location',{length:128}), availability: varchar('availability',{length:64}).default('unknown'), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const per_profile = pgTable('per_profile', { id: uuid('id').primaryKey().defaultRandom(), candidate_id: uuid('candidate_id').notNull(), headline: varchar('headline',{length:256}), skills: text('skills'), experience_years: integer('experience_years').default(0), resume_url: varchar('resume_url',{length:512}), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const org_company = pgTable('org_company', { id: uuid('id').primaryKey().defaultRandom(), name: varchar('name',{length:256}).notNull(), abn: varchar('abn',{length:32}), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const org_job = pgTable('org_job', { id: uuid('id').primaryKey().defaultRandom(), company_id: uuid('company_id').notNull(), title: varchar('title',{length:256}).notNull(), description: text('description'), location: varchar('location',{length:128}), salary_min: integer('salary_min'), salary_max: integer('salary_max'), status: varchar('status',{length:48}).default('open'), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const match_candidate_job = pgTable('match_candidate_job', { id: uuid('id').primaryKey().defaultRandom(), candidate_id: uuid('candidate_id').notNull(), job_id: uuid('job_id').notNull(), score: integer('score').default(0), outcome: varchar('outcome',{length:48}), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const evt_event = pgTable('evt_event', { id: uuid('id').primaryKey().defaultRandom(), topic: varchar('topic',{length:128}).notNull(), payload: text('payload').notNull(), attempts: integer('attempts').default(0), processed: boolean('processed').default(false), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
export const fin_ledger = pgTable('fin_ledger', { id: uuid('id').primaryKey().defaultRandom(), event: varchar('event',{length:128}).notNull(), amount_aud: numeric('amount_aud',{precision:12,scale:2}).notNull(), meta: text('meta'), created_at: timestamp('created_at',{withTimezone:true}).defaultNow() });
